linuxdeepin/deepin-fcitx5configtool-plugin

src/CMakeLists.txt
tests/CMakeLists.txt

build: fix build failure

---

debian/changelog

chore: bump version to 5.0.14

---

src/addim/configlib/model.cpp

Fixes linuxdeepin/developer-center#3679

feat: show IM name in tooltip

---

src/window/imsettingwindow.cpp

Open advanced setting page won't block mainwindow now. Event is not handled but accumulated and then handled after setting page is closed. Add a local event loop to consume events posted to mainwindow.
Log: fix open advanced setting page won't block

fix: open advanced setting page won't block

---

src/window/imsettingwindow.cpp
src/window/imsettingwindow.h

Fixes linuxdeepin/developer-center#3702

fix: actions are not displayed when hovering

---

debian/changelog

* Fix actions are not displayed when hovering
* Fix open advanced setting page block
* Improve keyboard layout indication
* Refactor the pages

chore: bump version to 5.0.15

---

CMakeLists.txt
src/CMakeLists.txt
src/fcitx5configplugin.cpp
translations/deepin-fcitx5configtool-plugin_en_US.ts

load translations in dde-control-center

chore: load translations in dde-control-center

---

debian/changelog

* load translations in dde-control-center

chore: bump version to 5.0.17

---

src/fcitx5Interface/advanceconfig.cpp
src/publisher/publisherfunc.cpp
src/publisher/publisherfunc.h
src/widgets/keysettingsitem.cpp
src/widgets/keysettingsitem.h
src/window/imsettingwindow.cpp

Fix setting shortcut failed when the delete key is included
Issues linuxdeepin/developer-center#6550, linuxdeepin/developer-center#6554, linuxdeepin/developer-center#6546

fix: setting shortcut failed

---

src/addim/configlib/model.cpp

fix: build errors

---

debian/control

chore: remove unused dependencies

---

debian/changelog

chore: bump version to 5.0.18

---

src/fcitx5Interface/advanceconfig.cpp
src/window/imsettingwindow.cpp

增加 NONE 选项
Issues linuxdeepin/developer-center#7302

fix: shortcut of "Scroll bewteen input methods" is wrong

---

src/window/imsettingwindow.cpp

删除选择的输入方式后，自动选中当前索引的输入方式（若有）， 或前一个输入方式
Issues: linuxdeepin/developer-center#7367

feat: 优化删除输入方式逻辑

---

debian/changelog
src/fcitx5Interface/advanceconfig.cpp

Issues: linuxdeepin/developer-center#7478

fix: will clear the shortcuts

---

src/main.cpp
src/window/imsettingwindow.cpp

auto resize with content
Issue: https://github.com/linuxdeepin/developer-center/issues/7728

fix: elide text

---

src/dcc-module/addimpage.cpp

Issues: linuxdeepin/developer-center#8849

chore: 修改打开应用商店的方式

---

debian/changelog

* chore: 修改打开应用商店的方式 (linuxdeepin/developer-center#8849)

chore: bump version to 5.0.22

---

src/dcc-fcitx5configtool/qml/IMList.qml
src/dcc-fcitx5configtool/qml/InputMethodsChooser.qml
src/dcc-fcitx5configtool/qml/ManageInputMethodsModule.qml
src/dcc-fcitx5configtool/qml/ShortcutsModule.qml

- Add input method chooser dialog for adding new input methods
- Implement input method list menu with move up/down and remove options
- Remove redundant padding in IMList delegate
- Add button to launch input method chooser dialog
The commit introduces UI components for managing input methods, including a dialog for selecting new input methods and context menu operations for existing ones. This lays the groundwork for implementing the actual input method management functionality.
Log: impl ui

feat: add input method management UI

---

src/dcc-fcitx5configtool/operation/fcitx5configtool.cpp
src/dcc-fcitx5configtool/operation/fcitx5configtool.h
src/dcc-fcitx5configtool/qml/InputMethodsChooser.qml
src/dcc-fcitx5configtool/qml/ManageInputMethodsModule.qml
src/lib/configlib/model.cpp

1. Change input method config structure from tree to flatten
2. Add input method selection and addition functionality
3. Implement search feature in input method chooser
4. Improve list view scrolling behavior and selection mechanism
This change makes the input method selection more user-friendly and provides better interaction experience.
Log: Impl InputMethodChooser

feat: improve input method selection interface

---

src/dcc-fcitx5configtool/operation/fcitx5configproxy.cpp
src/dcc-fcitx5configtool/operation/fcitx5configproxy.h
src/dcc-fcitx5configtool/operation/fcitx5configtool.cpp
src/dcc-fcitx5configtool/qml/DetailConfigItem.qml
src/dcc-fcitx5configtool/qml/KeySequenceDisplay.qml
src/dcc-fcitx5configtool/qml/ShortcutsModule.qml

- adjust IconButton layout and padding in DetailConfigItem
- add DBus service availability handling
- add option to filter global config options
- shortcut settings for input method switching
Log: improve key sequence input behavior

fix: improve key sequence input behavior

---

debian/changelog

chore: Bump version to 5.0.24

---

.reuse/dep5

chore: [reuse] copyright

---

debian/changelog

update veison 6.0.1
Log: update veison 6.0.1

chore: update veison 6.0.1

---

src/dcc-fcitx5configtool/lupdate_ts.sh
src/dcc-fcitx5configtool/qml/fcitx5configtool.qml
src/dcc-fcitx5configtool/translations/fcitx5configtool.ts
src/dcc-fcitx5configtool/translations/fcitx5configtool_az.ts
src/dcc-fcitx5configtool/translations/fcitx5configtool_bo.ts
src/dcc-fcitx5configtool/translations/fcitx5configtool_ca.ts
src/dcc-fcitx5configtool/translations/fcitx5configtool_es.ts
src/dcc-fcitx5configtool/translations/fcitx5configtool_fi.ts
src/dcc-fcitx5configtool/translations/fcitx5configtool_fr.ts
src/dcc-fcitx5configtool/translations/fcitx5configtool_hu.ts
src/dcc-fcitx5configtool/translations/fcitx5configtool_it.ts
src/dcc-fcitx5configtool/translations/fcitx5configtool_ja.ts
src/dcc-fcitx5configtool/translations/fcitx5configtool_ko.ts
src/dcc-fcitx5configtool/translations/fcitx5configtool_nb_NO.ts
src/dcc-fcitx5configtool/translations/fcitx5configtool_pl.ts
src/dcc-fcitx5configtool/translations/fcitx5configtool_pt_BR.ts
src/dcc-fcitx5configtool/translations/fcitx5configtool_ru.ts
src/dcc-fcitx5configtool/translations/fcitx5configtool_uk.ts
src/dcc-fcitx5configtool/translations/fcitx5configtool_zh_CN.ts
src/dcc-fcitx5configtool/translations/fcitx5configtool_zh_HK.ts
src/dcc-fcitx5configtool/translations/fcitx5configtool_zh_TW.ts

- Add description text for input method settings in QML
- Update lupdate command with -no-obsolete flag to remove outdated translations
- Add Chinese translation for the new description text
- Update translation files for all supported languages
Log: add description for input method settings and update translations

feat: add description for input method settings and update translations

---

src/dcc-fcitx5configtool/qml/DetailConfigItem.qml
src/dcc-fcitx5configtool/qml/ManageInputMethodsModule.qml
src/dcc-fcitx5configtool/translations/fcitx5configtool.ts
src/dcc-fcitx5configtool/translations/fcitx5configtool_az.ts
src/dcc-fcitx5configtool/translations/fcitx5configtool_bo.ts
src/dcc-fcitx5configtool/translations/fcitx5configtool_ca.ts
src/dcc-fcitx5configtool/translations/fcitx5configtool_es.ts
src/dcc-fcitx5configtool/translations/fcitx5configtool_fi.ts
src/dcc-fcitx5configtool/translations/fcitx5configtool_fr.ts
src/dcc-fcitx5configtool/translations/fcitx5configtool_hu.ts
src/dcc-fcitx5configtool/translations/fcitx5configtool_it.ts
src/dcc-fcitx5configtool/translations/fcitx5configtool_ja.ts
src/dcc-fcitx5configtool/translations/fcitx5configtool_ko.ts
src/dcc-fcitx5configtool/translations/fcitx5configtool_nb_NO.ts
src/dcc-fcitx5configtool/translations/fcitx5configtool_pl.ts
src/dcc-fcitx5configtool/translations/fcitx5configtool_pt_BR.ts
src/dcc-fcitx5configtool/translations/fcitx5configtool_ru.ts
src/dcc-fcitx5configtool/translations/fcitx5configtool_uk.ts
src/dcc-fcitx5configtool/translations/fcitx5configtool_zh_CN.ts
src/dcc-fcitx5configtool/translations/fcitx5configtool_zh_HK.ts
src/dcc-fcitx5configtool/translations/fcitx5configtool_zh_TW.ts

- Update title text from "Manage Input Methods" to "Input method management"
- Add description text for input method settings in QML
- Remove fixed width constraint from ComboBox for better dynamic sizing
- Update translation files for all supported languages
- Add -no-obsolete flag to lupdate command
- Fix Chinese translation for App Store button text
Log: improve input method settings UI and translations

fix: improve input method settings UI and translations

---

debian/changelog

update veison 6.0.2
Log: update veison 6.0.2

chore: update veison 6.0.2

---

src/dcc-fcitx5configtool/qml/DetailConfigItem.qml

- Add MouseArea to header for better click interaction
- Add backgroundType property for hover effect
- Fix code indentation and formatting
- Improve code readability with proper line breaks
- Remove trailing semicolon
Log:

feat: improve DetailConfigItem UI and code formatting

---

debian/changelog

chore: update version to 6.0.3

---

src/dcc-fcitx5configtool/qml/DetailAddonsItem.qml
src/dcc-fcitx5configtool/qml/IMList.qml

hidden label if text is empty
Log: fix ui bug
Bug: https://pms.uniontech.com/bug-view-297237.html

fix: [ui] Text not aligned with checkbox

---

src/dcc-fcitx5configtool/qml/InputMethodsChooser.qml

Add radius property to input method delegate items using DTK style control radius
Log: add rounded corners to input method items
Bug: https://pms.uniontech.com/bug-view-305833.html

fix: add rounded corners to input method items

---

src-old/src/dcc-module/translations/deepin-fcitx5configtool-plugin_fr.ts
src/dcc-fcitx5configtool/translations/fcitx5configtool_fr.ts

log: update translations.
bug: https://pms.uniontech.com/bug-view-333655.html

fix: update translations of fr
